[workspace]
# name = "repro"
# version = "0.1.0"
# edition = "2021"

# [[bin]]
# name = "pinger-server"
# path = "src/server.rs"

# [[bin]]
# name = "pinger-client"
# path = "src/client.rs"

members = [
  "server",
  "client",
  "lib"
]
